### ISSUE TITLE
신청한 카드 내역

### ISSUE THREAD

**Issue by yunki-kim** [card-monkey/card-monkey-BE#23]
GET "/paid/{id}"

신청 완료한 카드 조회

**Comment by crossbell8368** [comment]
## 20230215 작업내역

* PiadService/Paid paidRequest 에 메소드 작성
  * 기존에 저장된 Paid Entity 에서 List로 저장된 PaidCards 추출
  * 추출된 데이터를 paidResponseDTO에 저장 & List 형태로 return
