### ISSUE TITLE
카드 신청

### ISSUE THREAD

**Issue by yunki-kim** [card-monkey/card-monkey-BE#32]
POST "/card/{id}"

해당 카드를 신청함

**Comment by crossbell8368** [comment]
## 20230215 작업내역

* PiadService/Paid paidRequest 메소드 작성
  * 기존에 저장된 Paid Entity 추출 
  * 인자로 전달받은 card_id를 통해 해당 card 정보 추출 
  * Paid정보와 card정보를 PaidRequestDTO를 통해 병합 => list로 저장된 paidcards 에 add()
  * PaidRequestDTO를 Paid Entity로 변환 후 save()
